version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    networks:
      - app_network

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./templates:/usr/share/nginx/html
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
